version: '2'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=task
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root


  app:
    image: 'docker-spring-boot-postgres:latest'
    ports:
          - 8080:8080
    build:
      context: .
    container_name: app
    depends_on:
      - db
